#!/bin/bash
# Run on Pi on first boot
blk_dev="/dev/mmcblk0"
mntpt="/mnt/btrfs_root"
part_num="2"

part_start=$(parted "$blk_dev" -ms unit s p | grep "^${part_num}" | cut -f 2 -d: | sed 's/[^0-9]//g')


fdisk "$blk_dev" <<EOF
d
$part_num
n
p
$part_num
$part_start

p
w
q
EOF


mkdir $mntpt
mount "$blk_dev"p2 $mntpt

btrfs filesystem resize max $mntpt

umount $mntpt

size=$(parted -ms "$blk_dev"p2 unit B print free)
size=$(tail -1 <<< "$size" | cut -d ':' -f 2 | tr -d 'B')

exit $size